In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [5]:
df.sample(5)

    age  gender  fever   cough     city has_covid
50   19    Male  101.0    Mild    Delhi       Yes
70   68  Female  101.0  Strong    Delhi        No
26   19  Female  100.0    Mild  Kolkata       Yes
93   27    Male  100.0    Mild  Kolkata       Yes
96   51  Female  101.0  Strong  Kolkata       Yes

In [6]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [10]:
X_train

    age  gender  fever   cough       city
4    65  Female  101.0    Mild     Mumbai
45   72    Male   99.0    Mild  Bangalore
43   22  Female   99.0    Mild  Bangalore
59    6  Female  104.0    Mild    Kolkata
44   20    Male  102.0  Strong      Delhi
..  ...     ...    ...     ...        ...
80   14  Female   99.0    Mild     Mumbai
33   26  Female   98.0    Mild    Kolkata
48   66    Male   99.0  Strong  Bangalore
58   23    Male   98.0  Strong     Mumbai
5    84  Female    NaN    Mild  Bangalore

[80 rows x 5 columns]

# Aam Zindagi

In [12]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever= si.fit_transform(X_train[['fever']])

#also the test dat
X_test_fever = si.fit_transform(X_test[['fever']])
X_train.fever.shape

(80,)

In [13]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])

X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [16]:
# OneHotEncoding -> gender, city
ohe = OneHotEncoder(drop='first',sparse_output=False)

X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# also the test data
X_test_gender_city = ohe.transform(X_test[['gender', 'city']])

X_train_gender_city.shape

(80, 4)

In [17]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [18]:
X_train_transformed = np.concatenate(
    (X_train_age, X_train_fever, X_train_gender_city, X_train_cough),axis=1)

# also the test data
X_test_transformed = np.concatenate(
    (X_test_age, X_test_fever, X_test_gender_city, X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

# Mentos Zindagi

In [19]:
from sklearn.compose import ColumnTransformer

In [20]:
transformer = ColumnTransformer(transformers=[
    
    ('tnf1', SimpleImputer(strategy='most_frequent'), ['fever']),
    
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    
    ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['gender', 'city'])
    
], remainder='passthrough')

In [21]:
# Apply on training data
X_train_transformed = transformer.fit_transform(X_train)

In [23]:
# Apply on test data
X_test_transformed = transformer.transform(X_test)

In [24]:
X_train_transformed.shape

(80, 7)

In [25]:
X_test_transformed.shape

(20, 7)